allow opting out of dockerfile requirement for additional containers …
zendesk/samson pull request #2990
Opened 2018-10-09 18:09 UTC by grosser

…to ease migration

@rata does this work ?

if yes I'll add some tests and merge it ...

2018-10-09 19:39 UTC, grosser commented
also added support for getting container config from annotations via `container_foo_samson/dockerfile`

2018-10-10 04:47 UTC, klaus993 requested changes
Thanks, @grosser ! It works fine with the change I propose in my comment on the code, I suppose it must've been a simple error.

2018-10-10 04:47 UTC, klaus993 commented on plugins/kubernetes/app/models/kubernetes/template_filler.rb
> +        (index == 0 && ENV['KUBERNETES_ADDITIONAL_CONTAINERS_WITHOUT_DOCKERFILE'] ? 'none' : 'Dockerfile')
I analysed and tested this code and came to the conclusion that this code should be `index != 0` instead.

We want the `dockerfile` variable to be `'none'` only with the sidecar containers, don't we? So they don't get their image tag replaced. It's the first one the only one that has to have the hash inserted. This way it happens the other way round.

2018-10-10 05:02 UTC, grosser commented
ah yes :D

... I'll whip up some tests and docs then and get some more feedback!

On Tue, Oct 9, 2018 at 9:47 PM klaus993 <notifications@github.com> wrote:

> *@klaus993* requested changes on this pull request.
>
> Thanks, @grosser <https://github.com/grosser> ! It works fine with the
> change I propose in my comment on the code, I suppose it must've been a
> simple error.
> ------------------------------
>
> In plugins/kubernetes/app/models/kubernetes/template_filler.rb
> <https://github.com/zendesk/samson/pull/2990#discussion_r223935248>:
>
> >      end
>
>      private
>
> -    def build_selector_for_container(container, first:)
> -      dockerfile = container[:"samson/dockerfile"] ||
> -        (first && ENV['KUBERNETES_ADDITIONAL_CONTAINERS_WITHOUT_DOCKERFILE'] ? 'none' : 'Dockerfile')
> +    def build_selector_for_container(container, index:)
> +      dockerfile = samson_container_config(container, :"samson/dockerfile") ||
> +        (index == 0 && ENV['KUBERNETES_ADDITIONAL_CONTAINERS_WITHOUT_DOCKERFILE'] ? 'none' : 'Dockerfile')
>
> I analysed and tested this code and came to the conclusion that this code
> should be index != 0 instead.
>
> We want the dockerfile variable to be 'none' only with the sidecar
> containers, don't we? So they don't get their image tag replaced. It's the
> first one the only one that has to have the hash inserted. This way it
> happens the other way round.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zendesk/samson/pull/2990#pullrequestreview-163182582>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAsZ2kSxuykxm7iB226VjHxsgYh5NZOks5ujXvcgaJpZM4XT1gt>
> .
>

2018-10-10 12:01 UTC, rata commented
@grosser great! Doing the change for `index != 0` works for me too.

I've tried not using the env variable and just using the new annotations, and it didn't work. I see the annotations in the pod, like:

```
kind: Pod
metadata:
  annotations:
    container-heka-samson/dokerfile: none
    container-nginx-samson/dokerfile: none
```

But not sure why that seems not to be working. I've been trying to debug samson for a while now. Will continue and report bug, it sure is something silly :D

2018-10-10 12:01 UTC, rata commented
It's not a big problem, as I plan to use the variable first. But, to check the patch as a whole, I tried to check annotations too :)

2018-10-10 15:08 UTC, grosser commented
ah I did the annotation with underscores, but dashes are probably better
anyway

On Wed, Oct 10, 2018 at 5:02 AM rata <notifications@github.com> wrote:

> It's not a big problem, as I plan to use the variable first. But, to check
> the patch as a whole, I tried to check annotations too :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zendesk/samson/pull/2990#issuecomment-428545214>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAAsZ6mIdt_52405Y9sZiEtlKKPhGyHAks5ujeG1gaJpZM4XT1gt>
> .
>

2018-10-10 17:55 UTC, grosser commented
all fixed up and documented, looks good ?

2018-10-10 17:55 UTC, grosser commented
@zendesk/compute 👀

2018-10-10 20:38 UTC, klaus993 approved these changes
🚀 Works like a charm, although we will use the env var for simplicity, the other option works as well 😄 

It seems @rata was testing it with a typo in the annotation, he missed the `c` in `dockerfile`, I spotted that, changed it, tested, and only the first container is replaced.

Thanks!

2018-10-11 03:09 UTC, ragurney approved these changes

2018-10-11 03:09 UTC, ragurney commented on plugins/kubernetes/app/models/kubernetes/template_filler.rb
> +    def build_selector_for_container(container, index:)
`index` is a little confusing as an argument at first glance. What do you thing about passing a boolean `first` or `first_container` instead?

2018-10-11 03:17 UTC, grosser commented
yeah, good catch

On Wed, Oct 10, 2018 at 8:09 PM Ryan Gurney <notifications@github.com>
wrote:

> *@ragurney* approved this pull request.
> ------------------------------
>
> In plugins/kubernetes/app/models/kubernetes/template_filler.rb
> <https://github.com/zendesk/samson/pull/2990#discussion_r224302231>:
>
> >      end
>
>      private
>
> -    def build_selector_for_container(container)
> -      dockerfile = container[:"samson/dockerfile"] || 'Dockerfile'
> +    def build_selector_for_container(container, index:)
>
> index is a little confusing as an argument at first glance. What do you
> thing about passing a boolean first or first_container instead?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zendesk/samson/pull/2990#pullrequestreview-163634846>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAAsZzsj7sAxwVveVXLkffgzOr6x_WcEks5ujrZOgaJpZM4XT1gt>
> .
>

2018-10-11 04:16 UTC, merged