PAAS-3264 crud for namespaces
zendesk/samson pull request #3357
Opened 2019-05-11 02:44 UTC by grosser

@zendesk/samson @zendesk/compute 

Not ready for use yet, just splitting out a good chunk of the PR which makes sense on it's own

<img width="652" alt="Screen Shot 2019-05-10 at 7 42 08 PM" src="https://user-images.githubusercontent.com/11367/57564125-cbcdef80-735b-11e9-9f0e-f5d33851739d.png">
<img width="625" alt="Screen Shot 2019-05-10 at 7 42 16 PM" src="https://user-images.githubusercontent.com/11367/57564126-cbcdef80-735b-11e9-8459-434d9f293bda.png">
<img width="1171" alt="Screen Shot 2019-05-10 at 7 36 14 PM" src="https://user-images.githubusercontent.com/11367/57564127-cf617680-735b-11e9-895f-bc7413352670.png">
<img width="258" alt="Screen Shot 2019-05-10 at 7 35 45 PM" src="https://user-images.githubusercontent.com/11367/57564128-d4262a80-735b-11e9-930e-34c18825b075.png">
 
<img width="637" alt="Screen Shot 2019-05-10 at 7 35 40 PM" src="https://user-images.githubusercontent.com/11367/57564131-d9837500-735b-11e9-8242-3f51780a81e6.png">

2019-05-11 02:45 UTC, grosser commented on plugins/kubernetes/app/controllers/kubernetes/usage_limits_controller.rb
> -  before_action :set_resource, only: [:show, :edit, :update, :destroy, :new, :create]
does not have an edit action 🤷‍♂

2019-05-13 19:57 UTC, uthark requested changes

2019-05-13 19:57 UTC, uthark commented on plugins/kubernetes/app/controllers/kubernetes/usage_limits_controller.rb
> +  before_action :set_resource, only: [:show, :update, :destroy, :new, :create]
I guess, :update also should be removed.

2019-05-13 19:57 UTC, uthark commented on plugins/kubernetes/app/views/kubernetes/namespaces/_form.html.erb
> +      <%= form.input :project_ids, label: 'Projects', required: true do %>
It is optional.

2019-05-13 21:21 UTC, uthark approved these changes

2019-05-13 21:31 UTC, merged